version: '3'

services:
  puppeteer:
    build: .
    volumes:
    # mount code and output directories into the container
      - ./:/app
      - /app/node_modules
    working_dir: /app
    shm_size: 1gb #512M
    # just run the container doing nothing
    entrypoint: ["node", "index.js"]